### ISSUE TITLE
Reg. Code to run the algorithm

### ISSUE THREAD

**Issue by macsharma** [Teichlab/GPfates#1]
Dear sir,
Can you provide the helper code to run the GPfates on scRNA seq data.

**Comment by vals** [comment]
Hi,

This repository contains the helper code.

You probably need to be familiar with Python to run the methods.

When everything is installed, you can make an object which can be used for analysis by running

```
gpf = GPfates(sample_info, exp_matrix)
```

Where `sample_info` is a Pandas `DataFrame` of information per sample, and `exp_matrix` is a `DataFrame` containing genes in the rows and cells in the columns.

After this you can use the methods of `gpf` to perform different analysis (e.g. `gpf.infer_psuedotime()`). At the moment it is tailored to reproduce our results, so some code might need to be changed.

**Comment by macsharma** [comment]
Thanks
