### ISSUE TITLE
How to create file like "tcells_rebuttal.csv"

### ISSUE THREAD

**Issue by huidongchen** [Teichlab/GPfates#2]
Hi, Vals, 

Excellent package! 
In terms of running this tool in scRNA-seq data, how should I construct a sample infomation file like "tcells_rebuttal.csv" ? Can I still use this tool if I only have the gene expression data file and putative cell labels? Thanks!

**Comment by vals** [comment]
Hi!

The `tcells_rebuttal.csv` is just a file with a table of non-expression data for each cell. It's a handy way to keep phenotypic data and QC data to relate to expression values.

For the sake of using this package, the important bit is that row names in the phenotypic data file correspond to column names in the gene expression CSV file.

**Comment by huidongchen** [comment]
Hi, Vals,

Thanks a lot for your quick reply!  Sorry for my delay.
I'm attaching the sample information file and commands i'm using here. 

[sample_info.csv.zip](https://github.com/Teichlab/GPfates/files/1019144/sample_info.csv.zip)

> **sample_info = pd.read_csv('sample_info.csv', index_col=0)
> m = GPfates.GPfates(sample_info, expr_matrix)
> m.model_fates(X=['day'])**

Unluckily I'm still encountering the error ''KeyError: "['pseudotime'] not in index" after running this line 

> **m.model_fates(X=['day'])**


Did I miss anything in the sample information file? I would appreciate it if you could help me figure it out. Thanks.

**Comment by vals** [comment]
Hi,

The `model_fates` methods models `X` using `t` as a predictor. If you want to use your known time points, call the function as `m.model_fates(t='day')`.

A few points though:

Here `t` needs to be numbers, so you have to convert the strings like `T1` to `1.0` and `T2` to `2.0` etc.

You need to specify an `X` to model. If you know of a gene that will be different in the alternative fates, I suggest using the expression of this as `X`, at the vary least as a control to see what happens. Then you can include more genes, or use a latent variable representation of the data.

The values of such an `X` need to be added to the `m.s` dataframe. So for example, in our study we could have used Tcf7 as `X`. Then I would do

    >>> m.s['Tcf7'] = <Tcf7 expression values>
    >>> m.model_fates(t='day', X=['Tcf7'])

Hope this helps, let me know if it's unclear.

**Comment by huidongchen** [comment]
Awesome! It's working! 
Thanks a lot for your detailed explanation and that's really helpful! 👍
