### ISSUE TITLE
Bifurcation point is outside pseudotime range

### ISSUE THREAD

**Issue by koenvandenberge** [Teichlab/GPfates#5]
Hi,

I am running GPfates on a dataset where we are expecting a bifurcation.
After running the GPfates model, I let GPfates identify a branching point

```
logexp = pd.read_table('logCpm.txt', index_col=0, sep=' ')
sInfo = pd.read_table('sampleInfo.txt', index_col=0, sep=' ')

m = GPfates.GPfates(sInfo, logexp)
# perform GPLVM
m.dimensionality_reduction()
# store reduced dimensions
m.store_dr()
# get pseudotime
m.infer_pseudotime(s_columns=['bgplvm_0', 'bgplvm_1'])
# model trajectory
m.model_fates()
# identify bifurcation
p = m.identify_bifurcation_point()
```

However, the bifurcation point seems to be outside the range of pseudotime.

```
>>> print(p)
-4.384245904131617
>>> m.s.pseudotime.min()
-2.746186019966772
```

How does this happen? Does this mean that GPfates does not identify a bifurcation?
And, will the bifurcation statistics make any sense in that case?

Best,
Koen

**Comment by vals** [comment]
Hi Koen,

Hm.. this shouldn't happen, the range of possible `p` that are tested are between the smallest and largest pseudotime value: https://github.com/Teichlab/GPfates/blob/master/GPfates/gp_utils.py#L53

Can you compared `m.fate_model.X` with `m.s.pseudotime` and make sure they are the same? I might have made something not sync properly.

/Valentine

**Comment by koenvandenberge** [comment]
Thanks for the reply!
The values in those objects are indeed identical.
I re-checked and it seems that `infer_pseudotime` did not converge unless I give it prior information. I did not notice this initially; too used to seeing errors appear in red bold font from R..
Including prior information, the bifurcation point is indeed within the range of possible pseudotimes:

```
>>> print(p)
-2.2675396870183793
>>> m.s.pseudotime.min()
-2.821329523123369
```
